### ISSUE TITLE
WMS returns PNG images when requesting JPEG and GIF formats

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#10]
WMS 1.3.0 GetCapabilities document advertises that the GetMap request can return images in the image/png, image/jpeg and image/gif formats.  GetMap requests with parameter `FORMAT=image/jpeg` or `FORMAT=image/gif` returns images in PNG format (and `Content-Type: image/png` in the response header).

**Comment by prl900** [comment]
JPEG encoder pipeline process is already implemented: https://github.com/nci/gsky/blob/v0.6/processor/tile_jpg_enc.go

The most straight forward solution for this is would be to remove `image/jpeg` and `image/gif` from the GetCapabilities doc. @asedgmen are there cases were you think it would be useful to have jpeg tiles?

**Comment by bje-** [comment]
On the 0.6 branch (for now).

**Comment by asedgmen** [comment]
@prl900 preference would be to have PNG and JPEG support, although PNG support only would be adequate.  PNG is best for print quality maps and/or maps containing vector data, JPEG works well for maps containing imagery (smaller file sizes with comparable image quality) which has obvious benefits for the GSKY WMS delivering satellite imagery.
