### ISSUE TITLE
Invalid CRS defined in WMS GetCapabilities statement

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#11]
The CRS code `EPSG:WGS84(DD)` specified by the GetCapabilities document in element `/WMS_Capabilities/Capability/Layer/CRS` is not supported by GetMap requests.  The following error is returned in the response with 400 status: 

> …should contain a valid ISO 'crs/srs' parameter

This CRS code appears to have been adopted from GeoServer and is a throwback to an early version of WCS.  The code does not conform to the OGC WMS 1.3.0 spec for the EPSG namespace, which states in section 6.7.3.3: 

> “An “EPSG” CRS label comprises the “EPSG” prefix, the colon, and a numeric code.”

**Comment by prl900** [comment]
Remove:
https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/templates/WMS_GetCapabilities.tpl#L81
https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/templates/WMS_GetCapabilities.tpl#L83

Also, add other EPSG codes to the list, such as EPSG:4326.

@asedgmen: If you have other projections that you want to have available through GSKY please let us know and we can include them to the list.
