### ISSUE TITLE
Default TIME not working for WMS GetMap requests

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#12]
Blank images are returned if the TIME parameter is not provided in GetMap requests for the twelve Landsat 5, 7 and 8 layers (at http://gsky.nci.org.au/ows).  The “default” attribute in the layer’s Dimension element in the GetCapabilities statement has the value of “current”, indicating the service should return the most recent layer data if the TIME parameter is omitted.

**Comment by prl900** [comment]
If no date is specified in the WMS GetMap parameter GSKY defaults to the first date specified in the layer config file:

https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/ows.go#L153

The parameters parser should consider the case `time=default`.

Also, right now the GetCapabilities template hardcodes `<Dimension name="time" default="current" ...`.

Two options here, leave `"current"` hardcoded and implement last date by doing `conf.Layers[idx].Dates[len(conf.Layers[idx].Dates)-1]` or make `default` parameter part of the WMS GetCapabilities config template.
