### ISSUE TITLE
WMS GetMap requests restricted to 256x256 pixels

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#13]
For the four Low Tide and High Tide layers, and the twelve Landsat 5, 7 and 8 layers (at http://gsky.nci.org.au/ows), GetMap requests are only successful when WIDTH and HEIGHT values are set to 256.  Other values result in highly distorted images.

Following is an example of a successful GetMap request for the "DEA Low Tide Composite 25m v2.0 true colour" layer, WIDTH and HEIGHT set to 256:

http://gsky.nci.org.au/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=hltc:low:tc&STYLES=&WIDTH=256&HEIGHT=256&FORMAT=image/png&CRS=EPSG:4326&DPI=120&MAP_RESOLUTION=120&FORMAT_OPTIONS=dpi:120&TRANSPARENT=TRUE&BBOX=-22.71167821964186828,150.01979382711141398,-22.26083150676329581,150.47064053998997224

Same request, with WIDTH and HEIGHT set to 500, image is corrupted:

http://gsky.nci.org.au/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=hltc:low:tc&STYLES=&WIDTH=500&HEIGHT=500&FORMAT=image/png&CRS=EPSG:4326&DPI=120&MAP_RESOLUTION=120&FORMAT_OPTIONS=dpi:120&TRANSPARENT=TRUE&BBOX=-22.71167821964186828,150.01979382711141398,-22.26083150676329581,150.47064053998997224

Note that the two Intertidal Extents Model layers do not have this problem.

**Comment by prl900** [comment]
This has been fixed in branch v0.6: https://github.com/nci/gsky/tree/v0.6
