### ISSUE TITLE
Unable to make WCS GetCoverage requests using OGC:CRS84

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#17]
For GSKY service endpoint http://130.56.242.16/ows, WCS GetCoverage requests with CRS=OGC:CRS84 (a supported CRS in the DescribeCoverage statement) fail with (abridged) error message:
> Request ..... should contain a valid ISO 'crs/srs' parameter. 

Note that successful GetCoverage requests can be made using the EPSG:4326 CRS, provided in the `/CoverageDescription/CoverageOffering/domainSet/spatialDomain/gml:RectifiedGrid` element of the DescribeCoverage statement, although this CRS is not stated as supported.

Example request with CRS=OGC:CRS84 (fail):
http://130.56.242.16/ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&COVERAGE=global:c5:frac_cover&CRS=OGC:CRS84&BBOX=-1.8,-0.9,1.8,0.9&FORMAT=GeoTIFF&WIDTH=10&HEIGHT=10

Same request with CRS=EPSG:4326 (success):
http://130.56.242.16/ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&COVERAGE=global:c5:frac_cover&CRS=EPSG:4326&BBOX=-1.8,-0.9,1.8,0.9&FORMAT=GeoTIFF&WIDTH=10&HEIGHT=10

**Comment by prl900** [comment]
GSKY expects CRS parameters to be passed as an EPSG code with format `EPSG:XXXX`, but we can certainly extend its functionalities to accept CRS expressed in different standards and forms.

With the purpose of understanding the urgency and priority for this bug: Are these requests coming from an specific client that needs to specify CRS with OGS notation? Or is this creating problems or affecting other programs or workflows?

**Comment by asedgmen** [comment]
From an OGC conformance point of view, any CRS advertised as supported in the [DescribeCoverage ](http://130.56.242.16/ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=DescribeCoverage&COVERAGE=global:c5:frac_cover)document (element `/CoverageDescription/CoverageOffering/supportedCRSs`) should be accepted in GetCoverage requests.  Similarly, all CRSs that are accepted by the GetCoverage request ought to be listed as supported CRSs in the DescribeCoverage document.

Given that OGC:CRS84 is not accepted in GetCoverage requests to this service and EPSG:4326 is, I suggest removing OGC:CRS84 from `/CoverageDescription/CoverageOffering/supportedCRSs` in the describe coverage documents and including EPSG:4326 (plus any other supported CRSs).

This will be an issue for applications that use the DescribeCoverage document to determine accepted CRSs, for example QGIS lists available CRSs advertised in the DescribeCoverage document when the user is selecting WCS layers.
