### ISSUE TITLE
WCS GetCoverage requests with large extents timing out

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#203]
GSKY WCS endpoints tested:
```
http://130.56.242.16/ows/geoglam
http://130.56.242.16/ows/dea/cloud_masking_agg
http://130.56.242.16/ows/dea/daily
```

GetCoverage requests with large extents (e.g. Australian continent) time out with a “Processing timed out” error, for both geotiff and netcdf formats, for example:

http://130.56.242.16/ows/dea/daily?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&FORMAT=GeoTIFF&COVERAGE=LS8:NBART:TRUE&TIME=2017-09-24T00:00:00.000Z&BBOX=112.5,-44.5,153.5,-10.3&CRS=EPSG:4326&RESPONSE_CRS=EPSG:4326&WIDTH=1000&HEIGHT=1000

**Comment by edisonguo** [comment]
The timeout is a configurable parameter on a per layer basis. In this demo server, In production environment, we will set it properly to allow certain reasonable user requests.
