### ISSUE TITLE
WCS DescribeCoverage doesn't display netcdf file option

### ISSUE THREAD

**Issue by kdruken** [nci/gsky#26]
WCS DescribeCoverage doesn't display the netcdf file option even though it is accepted as valid input option. 

E.g., 
http://130.56.242.16/ows?service=WCS&version=1.0.0&coverage=LS5:NBAR:TRUE&request=DescribeCoverage 

```
<supportedFormats>
<formats>GeoTIFF</formats>
</supportedFormats>
```

http://130.56.242.16/ows?crs=EPSG%3A4326&service=WCS&format=NetCDF&request=GetCoverage&height=256&width=256&version=1.0.0&BBox=148%2C-37%2C151%2C-34&Coverage=LS7%3ANBAR%3ATRUE&time=1999-08-05T00%3A00%3A00.000Z

**Comment by prl900** [comment]
WCS DescribeCoverage template at:
https://github.com/nci/gsky/blob/v0.6/templates/WCS_DescribeCoverage.tpl

Should be extended to include netcdf option:
```
<supportedFormats>
      <formats>GeoTIFF</formats>
      <formats>NetCDF3</formats>
</supportedFormats>
```
Note the specs say NetCDF3 but we might be returning NetCDF4...
