### ISSUE TITLE
`502 Server Error: Bad Gateway` when requesting 'large' bbox

### ISSUE THREAD

**Issue by khornlund** [nci/gsky#317]
`GetCoverage` requests for `landsat8_nbar_16day` cause an error for certain bbox values.

Here is an example of a working request using `(**134.00**, -37.00, 141.00, -35.00)`:
```
http://gsky.nci.org.au/ows/dea?version=1.0.0&request=GetCoverage&service=WCS&Coverage=landsat8_nbar_16day&BBox=134.0%2C-37.0%2C141.0%2C-35.0&time=2017-12-27T00%3A00%3A00.000Z&crs=EPSG%3A4326&format=GeoTIFF&width=2556&height=2570&Styles=fc
```

And a broken request using `(**133.00**, -37.00, 141.00, -35.00)`:
```
http://gsky.nci.org.au/ows/dea?version=1.0.0&request=GetCoverage&service=WCS&Coverage=landsat8_nbar_16day&BBox=133.0%2C-37.0%2C141.0%2C-35.0&time=2017-12-27T00%3A00%3A00.000Z&crs=EPSG%3A4326&format=GeoTIFF&width=2556&height=2570&Styles=fc
```

Perhaps it can't handle boxes over a particular size?

Kind Regards,
Karl

**Comment by edisonguo** [comment]
The requested `width` and `height` are limited to 512 per request. If either exceeds 512, you get the Bad Gateway error (not very friendly I know). If you want to request large bbox, please subdivide it into multiple requests. We need to put certain limits on the production service to constraint resource usage.

**Comment by khornlund** [comment]
I'm using `width=2556&height=2570` in the query, so does that mean the restriction applies to the number of pixels selected in the original data? If so, it will be quite hard for users to know the maximum size of the area they can request.

Are there different limits for the different layers/endpoints? I've used this resolution/bbox successfully for `MODIS Vegetation Fractional Cover 8-day v3.1`.

**Comment by edisonguo** [comment]
The restriction is applied to the `width` and `height` parameters to limit the number of pixels selected in the original data. In resource usage terms, these are essentially the memory and cpu consumption. To my knowledge, for large datasets such as landsat and sentinel2, `width` and `height` are capped at 512. For smaller datasets such as Geoglam, the restrictions are lifted to much higher numbers. However, I don't know the exact numbers. Ultimately these restrictions are set by the ops team as they manage the production deployment of gsky.
