### ISSUE TITLE
Checking for unneccesary width/height parameters?

### ISSUE THREAD

**Issue by dtpc** [nci/gsky#541]
Hi, 

I am having an issue with a GetCoverage request on NCI's gsky server. Is this the right place to report it?

This request returns the following error:
https://gsky.nci.org.au/ows/aster?Service=WCS&VERSION=1.0.0&REQUEST=GetCoverage&STORE=True&COVERAGE=Ferric_Oxide_Content&FORMAT=GeoTIFF&CRS=EPSG:4326&BBOX=133.5,-31.5,133.7,-31.3
```
should contain valid 'width' and 'height' parameters.
```

The WCS spec states that `WIDTH, HEIGHT` are not required if the interpolation method is "None", which is appears to be the [case](https://gsky.nci.org.au/ows/aster?Service=WCS&VERSION=1.0.0&REQUEST=DescribeCoverage&COVERAGE=Ferric_Oxide_Content).

From the WCS 1.0.0 spec:
> Either these parameters or RESX, RESY, RESZ are normally required. However, if the Capabilities XML reports only the Interpolation method “None” for the queried coverage, then GetCoverage requests must be for the full native resolution of the data; they may not use RESX, RESY, RESZ or WIDTH, HEIGHT, DEPTH to change the coverage resolution. In this case, BBOX alone is used for subsetting. 

The param check looks to be here: https://github.com/nci/gsky/blob/master/ows.go#L734

Is it possible for me to make a `GetCoverage` request for a given BBOX at the native resolution without having to calculate the width/height?

Many thanks,

Dave

**Comment by edisonguo** [comment]
We're aware of the problem. At this stage it's not possible to make a `GetCoverage` request without width/height. In other words, one has to calculate width/height for the resolution they want to request.
But like you said, width/height are required by the spec. So it's convenient if the width/height of native resolution can be calculated on the server side. We might consider this feature in future releases if we get more interest from the community.
