### ISSUE TITLE
Clipping/mask WMS GetMap output dynamically using geometry passed in url params

### ISSUE THREAD

**Issue by erick-otenyo** [nci/gsky#546]
Hello,

I was wondering if this is something that can be implemented. If a wkt geometry (polygon/multipolygon) could be passed in the url parameter and then used to do some sort of masking dynamically? 
Maybe as reference, Geoserver mentions they support this kind of clipping through a WMS vendor param.

Regards

**Comment by edisonguo** [comment]
We currently have no plan for the clipping/mask feature for WMS GetMap, although I agreed it's an interesting feature. If the community generates large interest in this feature, we might consider it in the future.
