### ISSUE TITLE
All the documentation is gone! Dead project?

### ISSUE THREAD

**Issue by gaellafond** [nci/gsky#548]
Is this project dead?

The official documentation page was deleted:
https://opus.nci.org.au/display/Help/GSKY+User+Guide

I found a whole website dedicated at GSKY documentation, completely wiped out:
https://gsky.readthedocs.io/

The sample data page is broken: **Account suspended**
http://www.geo-rapp.org/rapp-monitor/

I spent about 1 hour trying to visualise anything in GSKY. Files hosted on S3, the small NetCDF files that comes with the docker image, etc. I could not get anything to work. It's pretty hard to figure out how to use the product when all the documentation has been removed.

**Comment by edisonguo** [comment]
GSKY is no longer under active development. If you want something similar, I'd suggest you to take a look at https://github.com/opendatacube/datacube-ows which is actively developed and maintained by a larger community.

**Comment by gaellafond** [comment]
Thanks @edisonguo
