### ISSUE TITLE
GetCapabilities request VERSION parameter should be optional

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#6]
GetCapabilities requests require the VERSION parameter to successfully return a GetCapabilities document.   VERSION parameter is optional according to following excerpt from section 6.2.4 of the OGC WMS 1.3.0 specification: 

> In response to a GetCapabilities request (for which the VERSION parameter is optional)
> that does not specify a version number, the server shall respond with the highest version it supports.

**Comment by prl900** [comment]
Change the contents of this if clause to write &"1.3.0" in case of `nil`

https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/ows.go#L106

**Comment by asedgmen** [comment]
@prl900 @bje just wondering if the changes carried out to make version parameter optional for WMS GetCaps requests also apply to WCS GetCapabilities requests.  I've since discovered that WCS has the same issue, i.e. VERSION parameter must be provided (using http://130.56.242.16/ows).  I can open a new issue if required.   Thanks.

**Comment by edisonguo** [comment]
@asedgmen The code changes to make VERSION optional only applies to WMS at the moment. Are you sure VERSION is also optional in WCS standards?

**Comment by asedgmen** [comment]
@edisonguo  Yes, Table 2 in the WCS 1.0.0 specification ([OGC 05-076](https://portal.opengeospatial.org/files/05-076)) has the VERSION parameter as optional.   Later WCS versions (1.1.1, 2.0.1) use the ACCEPTVERSIONS parameter instead of VERSION, which is still optional.
