### ISSUE TITLE
Ambiguity as to whether WMS 1.1.1 is supported

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#7]
It is unclear whether WMS 1.1.1 supported.  Issuing a GetCapabilities request without a VERSION parameter returns the following error message suggesting 1.1.1 is supported:

> This server can only accept WMS requests compliant with **version 1.1.1** and 1.3.0: /ows?request=GetCapabilities&service=WMS

Submitting a GetCapabilities request with VERSION=1.1.1 returns a 1.3.0 statement.

**Comment by prl900** [comment]
Yes, this is a known issue and the reason for the mixing WMS 1.1.1 and 1.3.0 is to solve a problem with the WMS definition in TerriaJS. The original issue is here:
https://github.com/TerriaJS/terriajs/issues/2590

This problem needs to be solved on TerriaJS side first if we want to assure compatibility.
