### ISSUE TITLE
WMS 1.3.0 GetCaps XML Schema validation errors

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#8]
WMS 1.3.0 GetCapabilities document has the following XML Schema validation errors:

- `/WMS_Capabilities/Service/ContactInformation/ContactPersonPrimary/ContactPerson` element is missing

- `/WMS_Capabilities/Service/ContactInformation/ContactAddress/PostCode` element is missing

**Comment by prl900** [comment]
@asedgmen Is this required to be WMS 1.3.0 compliant?

**Comment by asedgmen** [comment]
Yes.  The XML Schema definition (XSD) is part of the OGC WMS 1.3.0 specification, so failure to validate against the XSD can be considered non-compliance against the specification.
