### ISSUE TITLE
WMS GetCaps POST request fails

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#9]
WMS 1.3.0 GetCapabilities request using the POST method with the URL provided in the `/WMS_Capabilities/Capability/Request/GetCapabilities/DCPType/HTTP/Post/OnlineResource` element of the GetCaps document fails with message:

> Not a valid OWS request. URL /ows does not contain a valid 'request' parameter.

POST body:
```
<?xml version="1.0" ?>
<ows:GetCapabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows"
    xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsGetCapabilities.xsd">
    <ows:AcceptVersions>
        <ows:Version>1.3.0</ows:Version>
    </ows:AcceptVersions>
</ows:GetCapabilities>
```
Does the POST request for the GetCapabilities operation need to be supported?  If not, suggest removing POST OnlineResource element from the GetCaps statement.

**Comment by prl900** [comment]
I'm not aware of any application making use of POST for any of the WMS functionalities. I agree we should remove the part that publishes POST capabilities:

I think we should remove:
https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/static/schemas/wms/1.1.1/capabilities_1_3_0.xsd#L261

And from:
https://github.com/nci/gsky/blob/cd00fd3c608401b860748c187b703ddc6439577f/static/schemas/wms/1.1.1/capabilities_1_3_0.xsd#L280

@asedgmen Could you please provide the complete url that you used to send the POST request to? We'll use that to verify that the problem has been fixed.

**Comment by asedgmen** [comment]
I used the URL provided in the `/WMS_Capabilities/Capability/Request/GetCapabilities/DCPType/HTTP/Post/OnlineResource` element of the GetCaps document, i.e.  http://gsky.nci.org.au/ows?SERVICE=WMS&

The POST request was issued using the Postman application, with request header `Content-Type: application/xml`.
